#!/usr/bin/env python3

dice = []

import colors as c
import time
import random

dice.append('''
 -------
|       |
|   o   |
|       |
 -------
''')

dice.append('''
 -------
|o      |
|       |
|      o|
 -------
''')

dice.append('''
 -------
|o      |
|   o   |
|      o|
 -------
''')

dice.append('''
 -------
|o     o|
|       |
|o     o|
 -------
''')

dice.append('''
 -------
|o     o|
|   o   |
|o     o|
 -------
''')

dice.append('''
 -------
|o     o|
|o     o|
|o     o|
 -------
''')

while True:
    die = random.choice(dice)
    print(c.clear + c.random_color() + die + c.reset)
    input()

