#!/usr/bin/env python3

import colors as c
from utils import ask

text = '''
Amusement Park

Ahh {amusementpark}, a fun place to go to. So many rides and games.
We go there to {verb}. There is so much fun and exitment!
When there is {adj1} weather, it is a {adj2} trip. But either way they can still
be fun. You eat lots of {food} at the park. Sometimes it makes you sick.   
'''

words = {
    "amusementpark" : None,
    "adj1" : None,
    "verb" : None,
    "adj2" : None,
    "food" : None
}    

for keyword in words:
    words[keyword] = ask(keyword.rstrip('0123456789') + ': ')

print(words)

print(c.clear + text.format(**words))
