#!/usr/bin/env python3

import colors as c
from utils import ask

print(c.clear + c.red + '''
Welcome to the madlibs PROGRAM!
''' + c.reset)
 
text = '''
Ahh {amusment_park}, a fun place to go to. So many rides and games. We go there to {verb}. There is so much fun and exitment!
When there is {adj1} weather, it is a {adj2} trip. But either way they can still be fun.
'''

words = {
    "amusement_park" : {},
    "adj1" : {},
    "verb" : {},
    "adj2" : {}
}    

answers = {}

for key in words:
    answer = ask("Enter " + key + ": ")
