#!/usr/bin/env python3

import colors as c

print(c.clear + c.red + 'Mmmmmmmm,multiplication tables!')
print('Number')
number = input('Which number?')
print('Table for ' + number)

for multiplier in range(13,1,-1):
    product = int(number) * multiplier
    form = '{} x {} = {}'
    print(form.format(number,multiplier,product))
