#!/usr/bin/env python3

import colors as c
import fluffy as quiz
from utils import ask
import random

print(c.clear + c.magenta + '''
'Welcome to the QUIZ game!')
''' + c.reset)

print(quiz.intro)


while quiz.questions:
    question_function = random.choice(quiz.questions)
    is_correct = question_function()
    if is_correct:
        quiz.questions.remove(question_function)    
