#!/usr/bin/env python3

import time
import colors as c

seconds = 0
hundredths = 0
minutes = 0

while True:
    print(c.clear + c.cyan + '[Control-C to stop] ' + c.reset)
    print(seconds)
    print(hundredths)
    print(minutes)
    print(hours)
    time.sleep(0.01)
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    
    if seconds == 60:
       minutes += 1

    

